// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEupizSh5UuDLm1QQi3P-CfZGGgvMwWZw',
    appId: '1:121024571562:web:1749cd529c912d886d48d3',
    messagingSenderId: '121024571562',
    projectId: 'goldmapapp-e1c30',
    authDomain: 'goldmapapp-e1c30.firebaseapp.com',
    storageBucket: 'goldmapapp-e1c30.firebasestorage.app',
    measurementId: 'G-CM00JYLHPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19YC_Ff-aAJxBwTrcU9AtZbqJG7xxPzQ',
    appId: '1:121024571562:android:b06c713773492f2e6d48d3',
    messagingSenderId: '121024571562',
    projectId: 'goldmapapp-e1c30',
    storageBucket: 'goldmapapp-e1c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_xurYANt2l7V4oDhVMtjEEjJOYeAPfkY',
    appId: '1:121024571562:ios:83052461baa896f16d48d3',
    messagingSenderId: '121024571562',
    projectId: 'goldmapapp-e1c30',
    storageBucket: 'goldmapapp-e1c30.firebasestorage.app',
    iosBundleId: 'com.goldmap.goldmapapp',
  );
}
